version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: ./requirements.txt

# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
    
sphinx:
  fail_on_warning: true

formats:
  - pdf
